version: "3"

services:

  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: elasticsearch
    ports:
      - 9200:9200
    expose:
      - 9200

  kibana:
    image: kibana:7.17.0
    container_name: kibana
    ports:
      - 5601:5601
    expose:
      - 5601
    links: # Links kibana service to the elasticsearch container
      - elasticsearch
    depends_on:
      - elasticsearch
    environment: # Defined host configuration
      - ELASTICSEARCH_HOSTS=http://192.168.56.3:9200

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - elasticsearch
    container_name: fluentd
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      - elasticsearch
