version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    logging:
      driver: "fluentd"
      options:
        fluentd-address: FLUENTD_IP:24224   # docker inspect fluentd
        tag: fluent