version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.56.3:24224
        tag: fluent